services:
  postgres:
    image: postgres:17
    container_name: aman-foundation-postgres
    restart: always
    environment:
      POSTGRES_USER: amanfoundationuser
      POSTGRES_PASSWORD: amanfoundation1234
      POSTGRES_DB: aman_foundation_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: